---
name: Lint and Test

on:
  push:
    branches:
      - "main"
      - "feature/*"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r test-requirements.txt

      - uses: pre-commit/action@v3.0.0

      - name: Run Tests
        run: python -m pytest -v --cov --cov-report term-missing

      - name: Enfoce 100% Tests Coverage
        run: python -m coverage report --include 'tests/**' --fail-under 100
